server:
  port: 8070

logging:
  level:
    root: WARN

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 5000
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods: "*"
          routes:
            - id: auth-internal
              uri: no://op
              predicates:
                - Path=/api/v1/auth/internal/**
            - id: auth
              uri: http://localhost:8075
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - StripPrefix=1
            - id: order
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - StripPrefix=1
            - id: product
              uri: http://localhost:8085
              predicates:
                - Path=/api/v1/products/**
              filters:
                - StripPrefix=1
            - id: store
              uri: http://localhost:8090
              predicates:
                - Path=/api/v1/stores/**
              filters:
                - StripPrefix=1
            - id: customer
              uri: http://localhost:8095
              predicates:
                - Path=/api/v1/customers/**
              filters:
                - StripPrefix=1

security:
  keycloak:
    jwks-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/${KEYCLOAK_REALM:auth-app}/protocol/openid-connect/certs
    cache-ttl: 300000
    cache-timeout: 15000
    rate-limit-interval: 30000

client:
  auth:
    url: http://localhost:8075
    path: /v1/auth/internal/context
    api-key: ${API_KEY}