server:
  port: 8070

logging:
  level:
    root: WARN

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 1000
            response-timeout: 5000
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowedHeaders: "*"
                allowedMethods: "*"
          routes:
            - id: order
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - StripPrefix=1

auth:
  hmac:
    secret: ${AUTH_HMAC_SECRET}